### ISSUE TITLE
🛍️ Shopify Order Status: Mock order data

### ISSUE THREAD

**Issue by bangank36** [bangank36/shopify-order-status-editor#2]
## Summary
- Since we can not use `json` folder on `order` object in Shopify, need to mock these kind of data to the preview
Mock order data and other shopify object by create new filter in LiquidJs

```
// register new Filter
engine.registerFilter("jsonToObject", (json) => JSON.parse(json));
```

- Beside [liquidJs playground](https://liquidjs.com/playground.html#eyUgYXNzaWduIHBlb3BsZSA9ICJhbGljZSwgYm9iLCBjYXJvbCIgfCBzcGxpdDogIiwgIiAtJX0KCjx1bD4KeyUtIGZvciBwZXJzb24gaW4gcGVvcGxlICV9CiAgPGxpPgogICAgPGEgaHJlZj0ie3twZXJzb24gfCBwcmVwZW5kOiAiaHR0cDovL2V4YW1wbGUuY29tLyJ9fSI+CiAgICAgIHt7IHBlcnNvbiB8IGNhcGl0YWxpemUgfX0KICAgIDwvYT4KICA8L2xpPgp7JS0gZW5kZm9yJX0KPC91bD4K,e30=), can use [jumpseller](https://jumpseller.com/support/liquid-sandbox/) as reference

**Comment by bangank36** [comment]
## Mar 21 2023
- To display the data on the page, we need to implement these things
- [x] Implement `code` component using code-mirror #4
   https://github.com/bangank36/shopify-order-status-editor/blob/6127381b55d20b92cd383f592e652530951785f0/src/components/code/index.js#L9
- [x] Create 2 code component on the page, one to display the liquid injection #6 
   https://github.com/bangank36/shopify-order-status-editor/blob/6127381b55d20b92cd383f592e652530951785f0/src/pages/index.js#L87
- [x] Display the output code which is run against the mock order data #6 
   https://github.com/bangank36/shopify-order-status-editor/blob/6127381b55d20b92cd383f592e652530951785f0/src/pages/index.js#L60
- [x] Use react-liquidjs to create new json filter #6 
   https://github.com/bangank36/shopify-order-status-editor/blob/6127381b55d20b92cd383f592e652530951785f0/src/pages/index.js#L38

**Comment by bangank36** [comment]
## Mar 22 2023
- To start mocking order data, there are something to note about how Shopify parse these on the post order page
- Nit: some properties can be accessed directly `order_number, total_price`, like in [this page ](https://help.shopify.com/en/manual/orders/status-tracking/customize-order-status/add-conversion-tracking)
   - Follow up [topic](https://community.shopify.com/c/shopify-apis-and-sdks/explanation-of-the-order-number-value-in-the-checkout-script-for/td-p/1010631)
   - Turns out these variables are [available on liquid itself](https://guru-test-store.myshopify.com/pages/liquid-variables)
   - TODO: filter out these variables and check against their existing on post order page https://github.com/bangank36/shopify-order-status-editor/issues/5
- Note all properties of `order` object can be extracted directly by accessing by its name, such as: `order.customer` returned as `CustomerFromAddressableDrop`, it only reveal with `order.customer.email`
- I wrote a simple liquid code to identify [those props](https://shopify.dev/docs/api/liquid/objects/order), using `json` filter
```
{%  assign orderAttr = 'attributes,billing_address,cancel_reason,cancel_reason_label,cancelled,cancelled_at,cart_level_discount_applications,created_at,customer,customer_order_url,customer_url,discount_applications,discounts,email,financial_status,financial_status_label,fulfillment_status,fulfillment_status_label,id,item_count,line_items,line_items_subtotal_price,metafields,name,note,order_number,order_status_url,phone,shipping_address,shipping_methods,shipping_price,subtotal_line_items,subtotal_price,tags,tax_lines,tax_price,total_discounts,total_duties,total_net_amount,total_price,total_refunded_amount,transactions' %}
 {% assign my_array = orderAttr | split: "," %}
{% assign orderJson = '{}' %}

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    {% for key in my_array %}
      <tr>
        <td>{{ key }}</td>
        <td>{{ order[key] | json }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
```

## Un-parsable `order` props
|  Prop | Error | Notes |
|---|------|-------|
|  customer |   `{"error":"json not allowed for this object"} `  |    [docs](https://shopify.dev/docs/api/liquid/objects/customer)   |
|  metafields |   `{"error":"json not allowed for this object"} `  |   [docs](https://shopify.dev/docs/api/liquid/objects/metafield)    |
|  tax_lines |   `{"error":"json not allowed for this object"} `  |   [docs](https://shopify.dev/docs/api/liquid/objects/tax_line)    |
|  transactions |   `{"error":"json not allowed for this object"} `  |  [docs](https://shopify.dev/docs/api/liquid/objects/transaction)     |

**Comment by bangank36** [comment]
## Mar 22 2023
- Continue update on the liquid object on post order page
- Merchant can access to [checkout](https://shopify.dev/docs/api/liquid/objects/checkout) and [shop](https://shopify.dev/docs/api/liquid/objects/shop) object, besides `order` object, according to this [page](https://help.shopify.com/en/manual/orders/status-tracking/customize-order-status?shpxid=089f633d-C823-48E3-8457-E384BED71DBF)
- [x] List all checkout props and extract it to mockCheckout 
   https://github.com/bangank36/shopify-order-status-editor/blob/4e819b88517705cb84f94f11625666d9928181e7/src/mock/checkout.js#L6
- [x] List all shop props and extract it to mockShop
   https://github.com/bangank36/shopify-order-status-editor/blob/4e819b88517705cb84f94f11625666d9928181e7/src/mock/shop.js#L7
- [x] Create the variables mock data based those 3 mock https://github.com/bangank36/shopify-order-status-editor/issues/5

**Comment by bangank36** [comment]
Closed as relevant tickets has been solved. Should add more data into the comments if there are more insights
